CREATE DATABASE DOCUFY;
USE DOCUFY;

CREATE TABLE [USER]
(
	ID INT NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	EMAIL_ADDRESS VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE[BOOKS]
(
	ISBN VARCHAR(256) NOT NULL,

)